name: Continuos Integration

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Backend Images
        run: docker-compose build backend
      - name: Run Backend and Database Containers
        run: docker-compose up backend database -d
      - name: Run Test Backend Pipeline
        run: docker-compose exec backend poetry run test
