name: Continuos Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Images
        run: docker-compose build
      - name: Run Backend and Database Containers
        run: docker-compose up backend database
      - name: Run Test Backend Pipeline
        run: docker-compose exec backend poetry run test
